### 1. 이메일 인증 번호 발송
POST http://52.63.7.132:8080/api/auth/certification
Content-Type: application/json

{
  "email": "dbswns0312@naver.com"
}


### 2. 인증 번호 검증
POST http://localhost:8080/api/auth/verify
Content-Type: application/json

{
  "email": "dbswns0312@naver.com",
  "certificationNumber": "095530"
}


### 3.회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "schoolEmail": "dbswns0312@naver.com",
  "password": "password123!",
  "nickname": "명지대컴공"
}



### 4. 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "schoolEmail": "dbswns0ds312@naver.com",
  "password": "password123!"
}