### 로그인
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "schoolEmail": "{{email}}",
  "password": "{{password}}"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken);
%}
